binds {
	# Не работает
	pass_mouse_when_bound = false

	# Задержка, чтобы scrool_event в биндах ждал ввода
	scroll_event_delay = 300

	# При указании выбранной workspace переключает на последний выбранный
	workspace_back_and_forth = false

	# Прячет специальный воркспейс при изменении текущего
	hide_special_on_workspace_change = false

	# Разрешить прокручивать воркспейсы по кругу
	allow_workspace_cycles = true

	# Не работает. При смене workspace перемещать курсор в центр (0) или к последнему окну (1)
	workspace_center_on = 1

	# 0 - Фокус на последнем. 1 - фокус на самом большом
	focus_preferred_method = 0

	# Диспатчеры игнорируют лок на группах
	ignore_group_lock = false

	# При true фокус крутится только по fullscreen окнам
	movefocus_cycles_fullscreen = false
	# При true сначала прокручивается группа
	movefocus_cycles_groupfirst = false

	# Фокус или движение окна перепрыгивает на след. монитор
	window_direction_monitor_fallback = true

	# Полный перехват всех действий клавиатуры приложением
	disable_keybind_grabbing = true

	# hyprland игнорирует fullscreen для pinned окон. Это позволяет его использовать и возвращать обратно
	allow_pin_fullscreen = true
	
	# Сколько пикселей нужно пройти, чтобы сработал drag
	drag_threshold = 0
	
}
