cursor	{
	invisible = false

	# Синхронизирует тему курсора gtk с xcursor
	# Приложения могут запрашвать тему xcursor, а hypr использует другой набор тем
	sync_gsettings_theme = true

	# Использовать аппаратный курсор (через GPU), 1 - через процессор. 2 - когда разрывы
	no_hardware_cursors = 0
	
	# Variable refresh rate
	# При движении мыши hyprland рисует тот же кадр, но курсор в другом месте ->
	# больше FPS -> монитор переключается. 1 - отключает это
	# Может потребоваться no_hardware_cursors
	no_break_fs_vrr = 1

	# Минимальный фпс при движении мыши, при no_break_fs_vrr = 1
	min_refresh_rate = 24

	# После этих пикселей курсор не двигается к краю экрана.
	# Всё равно юужет виден
	hotspot_padding = 0

	# После этих секунд курсор скрывается
	inactive_timeout = 0

	# При true отключает перемещение мыши биндами
	no_warps = false

	# Курсор перемещается не в центр окна, а в последнюю позицию относительно этого окна
	persistent_warps = true

	# 1 - при переключении на workspace перемещает курсор на последнее окно
	# 0 - выключено, 2 - игнорировать no_warps
	warp_on_change_workspace = 1
	
	# Для special workspace
	warp_on_toggle_special = 1

	# Строка, на каком мониторе должен появляться курсор при старте
	# default_monitor 

	# Постоянный zoom на курсор
	zoom_factor = 1
	# Курсор всегда в центре зума
	zoom_rigid = true
	# zoom ведёт себя как камера в "В тылу врага"
	zoom_detached_camera = false

	# Использует темы для wayland и hyprland. вместо xcursor. fallback на xcursor
	enable_hyprcursor = true

	# Прятать курсор при нажатии клавиатуры до тех пор, пока курсор снова не сдвинется
	hide_on_key_press = false
	hide_on_touch = false
	hide_on_tablet = false

	# Использовать буфер CPU для hw отрисовки курсора. 2 - только для NVIDIA
	use_cpu_buffer = 0

	# Запоминать позицию курсора при управлении мышкой через клавиатуру и возвращать её при движении мыши
	warp_back_after_non_mouse_input = false

	# Отключить antialiasing при зуме
	zoom_disable_aa = true
}
