# Тут всё для дебага
debug {

	overlay = false

	# Подсвечивает изменённую область
	damage_blink = false

	# Дебаг для OpenGL
	gl_debugging = false

	# Не писать логи в файл
	disable_logs = true
	# Не писать время логов
	disable_time = true
	# Логи в stdout
	enable_stdout_logs = false

	# Перерисовывать только нужные пиксели дисплея. НЕ МЕНЯТЬ
	damage_tracking = 2

	# Установить в 1 и изменить в 0, чтобы крашнуть hyprland
	manual_crash = 0

	# Подавлять ошибки в файлах конфига hyprland
	suppress_errors = false

	# Если hyprland завис на обработке системного или внутреннего сигнала дольше, чем на это количество секунд, то убивает процесс hyprland
	# watchdog_timeout = 5
	
	# Убирает проверку scale фактора. Будут ошибки в расположении пикселей
	disable_scale_checks = true

	# Сколько ошибок конфига показывать
	error_limit = 10
	# 0 - сверху, 1 - снизу
	error_position = 0

	colored_stdout_logs = true

	# Визуально отображает очередь отрисовки
	pass = false

	# Включить все функции cm
	full_cm_proto = true

	# invalidate_fp16 = 2
}
