ecosystem {
	# Уведомление об обновлении
	no_update_news = false
	# Уведомление о пожертвовании
	no_donation_nag = true

	# Использовать разрешения hyprland для программ
	enforce_permissions = false
}
