general {
	# Размер рамки окна
	border_size = 2
	# рамка у плавающего окна
	#no_border_on_floating = false
	# расстояние между окнами
	gaps_in = 3
	# расстояние между окном и экраном
	gaps_out = 5
	# Не работает! Расстояние между плавающим окно и экраном при перемещениях
	float_gaps = 10,10,10,10

	# хз, не работает
	# Должны быть гапы от workspace'ов
	gaps_workspaces = 100
	
	# цвет рамки неактивного окна
	col.inactive_border = rgba(33ccffff) rgba(00ff99ff) 45deg
	# цвет рамки активного окна
	col.active_border = rgba(ff0000ff) rgba(9900ffff) 90deg
	
	# движок окон. dwindle - окна в клеточку, master - одно вертикальное, остальные стопками
	layout = dwindle

	# Не переключать фокус, при попытке перейти границу экрана
	no_focus_fallback = true
	# Не работает
	resize_on_border = false
	# размер области, за которую можно схватить
	extend_border_grab_area = 0
	# угол, для resize_on_border, 0 - отключено, далее по часовой с левого верхнего
	resize_corner = 0
	# позволить разрывать кадры
	allow_tearing = false

	# Не работает
	modal_parent_blocking = false

	# плавающие окна
	snap {
	enabled = true
	# когда прилимать к окну
	window_gap = 20
	# когда прилипать к краю экрана
	monitor_gap = 50
	# граница уходит за экран
	border_overlap = false
	# при border_overlap учитывать general:gaps_in
	respect_gaps = true
	}
}
