group {
	auto_group = true
	insert_after_current = true
	# Переключать фокус на окно вне группы
	focus_removed_window = true

	# Перетаскивание окна добавляет его в группу
	# 0 - выключено, 1 - да, 2 - только при перетягивании в groupbar
	drag_into_group = 1
	# Сливать группы при перетаскивании
	merge_groups_on_drag = true
	# Для groupbar
	merge_groups_on_groupbar = true
	# Добавлять ли плавающие окна
	merge_floated_into_tiled_on_groupbar = false
	# При использовании movetoworkspace сливает окно с одиночной группой
	group_on_movetoworkspace = false


	# Края
	col.border_active = rgba(255,0,255,1)
	col.border_inactive = rgba(0,255,255,1)

	col.border_locked_active = rgba(255,0,0,1)
	col.border_locked_inactive = rgba(0,0,255,1)

	
	groupbar {
		enabled = true
		
		# Использует misc:font_family если не задан
		# font_family
		font_size = 14
		font_weight_active = ultraheavy
		font_weight_inactive = normal

		height = 14
		

		indicator_gap = 0
		indicator_height = 0
		
		# Отображать вкладки сверху вниз
		stacked = false

		# Не работает
		priority = 1

		# Показывать имена окон
		render_titles = true

		# Вертикальное смещение
		text_offset = 0
		# Горизонтальное смещение
		text_padding = 10

		# Позволять ли на скролл переключать вкладки
		scrolling = true

		# Индикатор
		rounding = 1
		rounding_power = 2
		
		
		gradients = true
		gradient_rounding_power = 2
		gradient_rounding = 10
		
		# Скруглять только крайние углы индикатора
		round_only_edges = false
		gradient_round_only_edges = true
		
		# Между табами
		gaps_in = 5
		# Между табами и окнами
		gaps_out = 5
		
		# Удаляет верхний отступ
		keep_upper_gap = false
		# Работает только для неактивных групп
		blur = false
	
		col.active = rgba(255,0,90,1)
		col.inactive = rgba(50,100,150,1)

		col.locked_active = rgba(255,0,0,1)
		col.locked_inactive = rgba(0,0,255,1)
	}
}
