background = rgba(20,20,50,1)

base = rgba(0,50,75,1)
text = rgba(200,200,200,1)

alternate_base = rgba(0,200,255,1)

bright_text = rgba(255,255,255,1)

accent = rgba(255,75,75,1)
accent_secondary = rgba(255,255,0,1)

h1_size = 24
h2_size = 20
h3_size = 16

font_size = 12
small_font_size = 10

font_family = arial
font_family_monospace = monospace

rounding_large = 15
rounding_small = 7
