# Собирает всё воедино
source = ~/.config/hypr/hypr.general
source = ~/.config/hypr/hypr.default
source = ~/.config/hypr/hypr.decoration
source = ~/.config/hypr/hypr.input
source = ~/.config/hypr/hypr.group

source = ~/.config/hypr/hypr.monitors
