general {
	hide_cursor = false
	ignore_empty_input = true

	# Моментально рисовать виджеты
	immediate_render = false

	text_trim = true
	
	# 0 -выключено, 1 - включено, 2 - авто
	fractional_scaling = 2
	# 0 - GPU, 1 - CPU. Что использовать для скринщота экрана
	screencopy_mode = 0
	
	# Сколько ждать после неудачной попытки
	fail_timeout = 2000
}


auth {
	pam {
		enabled = true
		module = hyprlock
	}
	fingerprint {
		enabled = false
		ready_message = Scan fingerprint to unlock
		present_message = Scanning fingerprint
		retry_delay = 500
	}
}

animations {
	enabled = true
}

image {
	# path = /etc/hyprlock/user/ixoroturg.png
	path = /home/ixoroturg/.config/hypr/hyprlock/ixoroturg.png
	
	size = 300

	# -1 - круг
	rounding = -1

	border_size = 0
	# border_color = rgba(0,0,0,1)

	
	position = 0, 100
	valign = center
	halign = center
	zindex = -1

	shadow_passes = 5
	shadow_size = 10
	shadow_color = rgba(0,255,255,1)
	shadow_boost = 4
}

background {
	
	monitor =
	path = screenshot
	# color = rgba(100,0,0,1)
	# color = rgba(255,255,255,1)
	blur_size = 5
	blur_passes = 4

	noise = 0
	contrast = 2
	brightness = 1
	vibrancy = 1
	vibrancy_darkness = 1

	# -1 - выключено. 0 - перезагружать картинку при SIGUSR2. Остальное - секунды смены картинок
	reload_time = -1
	# Команда для получения нового пути
	# reload_cmd = 
	
	# За сколько секунд менять картинку для плавности. < 0 отключает функцию
	crossfade_time = -1
	zindex = -1

}
# shape {
#     monitor =
#     size = 360, 60
#     color = rgba(0, 0, 0, 0.0) # no fill
#     rounding = -1 # circle
#     border_size = 4
#     border_color = rgba(0, 207, 230, 1.0)
#
#     position = 0, 80
#     halign = center
#     valign = center
#
# }

shape {
	size = 1920, 32
	valign = top
	halign = center
	xray = true
	zindex = 5
}


label {
	zindex = 1
	halign = left
	valign = center
	position = 400, 100

	font_size = 40


	text = Язык: $LAYOUT[en,ru,jp]
}
shape {

	border_size = 10
	border_color = rgba(0,200,255,1)

	rounding = -1
	
	zindex = 0
	halign = left
	valign = center
	position= 360,95
	size = 280,90
}

label {
	zindex = 1
	halign = center
	valign = top
	position = 0, -100

	font_size = 40

	text = $TIME
}
shape {
	border_size = 10
	border_color = rgba(255,0,0,1)

	rounding = -1

	zindex = 0
	valign = top
	halign = center

	position = 0, -85
	size = 200,90
}

input-field {
	monitor =
	size = 300, 50

	# hide_input = true

	check_text = Проверка ...

	fail_text = Неправильно, $ATTEMPTS / 5
	
	placeholder_text = Введите пароль
	position = 0, -120
	halign = center
	valign = center

}
