input {
	# вроде как пресеты
	# kb_rules = evedv
	# физическая модель клавиатуры
	kb_model = pc105
	# раскладки клавиатуры
	kb_layout = us,ru
	# варианты раскладки клавиатуры
	kb_variant = ,winkeys
	# доп настройки. Переключение языка на alt+shift, shift вводит напрямую большие символы, и shift не прерывает caps. правый alt в качестве кнопки compose, menu (кнопка справа для вызова ПКМ) в качестве кнопки hyper
	kb_options = grp:alt_shift_toggle,caps:internal_nocancel,compose:ralt,hyper:menu,caps:escape_shifted_capslock 


	# numlock выключен при включении ПК
	numlock_by_default = false
	# считывать кнопки по символу
	resolve_binds_by_sym = false

	
	repeat_rate = 25
	repeat_delay = 500

	
	sensitivity = -0.5
	accel_profile = flat
	force_no_accel = true

	# Такого нет
	rotation = 0
	# Меняет местами LBM и RBM
	left_handed = false

	# scroll_points = 
	scroll_method = 2fg
	# скролить на кнопку
	# scroll_method = on_button_down
	# кнопка скролла, 0 по умолчанию, 84 - 5 на NumPad. Клавиатура не работает
	scroll_button = 0
	# позволяет заблокировать кнопку. Она будет переключаться между скроллом и не скроллом. В режиме скролла движения мыши воспринимаются как скролл
	scroll_button_lock = false
	scroll_factor = 1
	natural_scroll = false

	# при движении мышь переключает фокус на окно под собой
	follow_mouse = 1
	# сколько должна пройти мышь над окном, чтобы установить фокус
	follow_mouse_threshold = 0
	# при закрытии окна фокус переводится на окно под курсором
	focus_on_close = 1
	# мышь постоянно переключает фокус, а не только при пересечении границ
	mouse_refocus = true
	# при 1 переводит фокус с плавающего на обычное окно, при 2 переводит фокус также между плавающими окнами
	float_switch_override_focus = 2
	# при true, имея только плавающие окна в special workspace не блокирует фокус на обычном workspace
	special_fallthrough = false

	# 0 - ничего, 1 - курсор посылает события перемещения, когда не на окне. 2 - курсор посылает самые координаты к окну. 3 - перемещает курсор к 2.
	off_window_axis_events = 0

	emulate_discrete_scroll = 0


}

device {
	# Мой ноут
	name = at-translated-set-2-keyboard
	kb_model = asus_laptop
}

device {
	name = 2.4g-mouse-1
	scroll_method = no_scroll
}
