layout {
	# Соотношение сторон окна, когда оно одно на весь экран
	single_window_aspect_ratio = 0 0
	# Если отступ меньше, чем этот процент экрана, то его не будет
	single_window_aspect_ratio_tolerance = 0.1
	
}
