misc {
	# Отключает стандартные обои
	disable_hyprland_logo = false
	# Отключает текст снизу
	disable_splash_rendering = false

	# Уведомление, что монитор не может использовать scale
	disable_scale_notification = false

	# Цвет текста снизу
	# col.splash = 
	
	font_family = sans
	# Шрифт для текста снизу
	splash_font_family = sans
	
	# Установить конкретные стандартные обои
	force_default_wallpaper = 2

	# Variable frame rate. Снижает FPS в простое
	vfr = true
	# Variable refresh rate. Вертикальная синхронизация
	vrr = 0

	# Display power management signaling. Сигнал монитору на уход в спящий режим
	mouse_move_enables_dpms = true
	key_press_enables_dpms = true

	# При создании клавиатуры дать ей имя "клавиатура"-procName, вместо стандартного имени
	name_vk_after_proc = true

	# Фокус следует за drag-and-drop
	always_follow_on_dnd = true

	# При true оверлеи захватывают и не отпускают фокус клавиатуры при движении мыши
	# Не работает на wofi
	layers_hog_keyboard_focus = false
	
	# Не работает
	animate_manual_resizes = true
	animate_mouse_windowdragging = true

	# Выключить авто перезагрузку конфига
	disable_autoreload = false

	# Закрывать терминал при открытии программы и открывать его снова, при закрытии программы
	enable_swallow = false
	# На какие программы распространяется. Нужен обязательно
	swallow_regex = .*
	swallow_exception_regex = .*

	# Не перемещать фокус при запросе фокуса
	focus_on_activate = false

	# Фокус монитора (для глобальных действий) следует за мышью
	mouse_move_focuses_monitor = true

	# Перезапускать экран блокировки, если он упадёт
	allow_session_lock_restore = true

	# Показывать ли приложения на экране блокировки
	session_lock_xray = true

	# Цвет bg при выключенном изображении
	background_color = rgb(1,1,1)

	# Закрывать special workspace, если в нём нет окон
	close_special_on_empty = true

	# В fullscreen или maximized позволять ли приложениям перехватывать фокус при запросе
	# 0 - нет, 1 - да, 2 - выходить из фулскрина
	on_focus_under_fullscreen = 0

	# При true закрытие fullscreen окна переведётследующие окно в фулскрин
	exit_window_retains_fullscreen = false

	# Отслеживает workspace окна при его открытии родителем. Бесполезная
	initial_workspace_tracking = 0

	# Вставлять ли на среднюю кнопку
	middle_click_paste = false
	
	# FPS неактивного окна
	render_unfocused_fps = 10

	# Уведомления, если xdg управляется извне
	disable_xdg_env_checks = false

	# Уведомление, что hyprland-qtutils не установлено
	# disable_hyprland_qtutils_check = false
	
	# Задержка перед тем, как показать lockdead, чтобы блокировщик успел всё выписать. Максимум 5 сек.
	lockdead_screen_delay = 5000

	# Показывать диалог, что app not response
	enable_anr_dialog = false

	# Количество опросов перед anr_dialog
	anr_missed_pings = 5

	# Учитывать ли min_size и max_size при расположении окна в тайлинге
	size_limits_tiled = false

	# Уведомление о неиспользовании start-hyprland
	disable_watchdog_warning = false
}
