render {
	
	# В полноэкранном приложении позволяет получить прямой доступ к монитору
	direct_scanout = 1

	# При растягивании окна насильно растягивать его содержимое
	expand_undersized_textures = true
	
	# Отключает задний буфер для рендера картинки
	xp_mode = false

	# Анимация для изменения яркости при переключении дневного и ночного режима
	ctm_animation = 0

	# Заменяет фактические цвета такими, чтобы они выглядели естественными.
	# Мониторам нужно явно указывать цветовой профиль
	# Нужен для hdr и корректировки цвета
	# Color management
	cm_enabled = false
	# Автоматически ставить hdr в полном экране, нужен cm_enabled
	cm_auto_hdr = 1
	# Если нет шейдеров для cm, то использовать безшейдерный метод только для direct_scanout и passthrough
	non_shader_cm = 2
	# Внешние ctm (Color Transformation Matrix) - меняет цвета. 0 - выключено в фулскрине
	# non_shader_cm_interop = 0
	# standard dynamic range electro-optical transfer function. Гамма
	cm_sdr_eotf = srgb
	
	# Управлять ли профилями монитора в соответствии с типом контента
	send_content_type = false


	# Тройная буферизация
	new_render_scheduling = false



	# Приложения могут спрашивать задержку вывода изображения на экран
	commit_timing_enabled = true

	# Использовать буферы на 16 бит на канал цвета (2 - только при hdr), 0 - выключено, 1 - включено
	# use_fp16 = 2

	# Сохранять не изменённый sdr кадр для записи и скриншотов экрана
	# keep_unmodified_copy = 1
}
