screencopy {
	max_fps = 0

	# Путь к программе, которая должна включиться по порталу
	# custom_picker_binary = 
	
	# Использует не screen shared memory
	# При false использует VRAM. иначе RAM
	force_shm = false

	# Приложение запрашивает разрешение на запись экрана
	# Устанавливает галочку "Запомнить выбор" для этого приложения
	allow_token_by_default = true
}
