xwayland {
	enabled = true
	
	# При масштабировании использовать метод ближайшего соседа, вместо блюра
	use_nearest_neighbor = true

	# Форсирует scale в 1, на scale мониторах
	force_zero_scaling = false

	# Какой тип сокета. Абстрактный может не работать
	create_abstract_socket = false
}
