windowrule {
	name = ignore_fullscreen_events
	match:class = .*
	suppress_event = fullscreen maximize activate activatefocus fullscreenoutput
}

windowrule {
	name = clipse
	match:class = ^(clipse)$
	float = on
	move = (monitor_w*0.5-window_w*0.5) (monitor_h*0.5-window_h*0.5)
	size = 700 600
}

windowrule {
	name = spore
	# match:title = ^.*spore.*$
	match:class = ^(steam_app_17390)$
	fullscreen_state = 1 1
	suppress_event = fullscreen maximize activate activatefocus fullscreenoutput
	size = 1920 1080
	
}
