windowrule {
	name = ignore fullscreen events
	match:class = .*
	suppress_event = fullscreen, maximize, activate, activatefocus, fullscreenoutput
}

windowrule {
	name = clipse
	match:class = ^(clipse)$
	float = on
	move = (monitor_w*0.5-window_w*0.5) (monitor_h*0.5-window_h*0.5)
	size = 700 600
}
